version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "deps"

    labels:
      - "dependencies"

    # Group minor & patch updates
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    # Ignore unstable stuff
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"