name : server

on : 
  push : 
    branches : ["main"]

jobs : 
    build : 
        - name : Checkout
          uses : actions/checkout@v4

        - name : install dependencies
          run : npm install

        - name : build
          run : npm run build

    unit-test : 
        - name : Checkout
          uses : actions/checkout@v4
  
        - name : install dependencies
          run : npm install
  
        - name : build
          run : npm run build
