name : Frontend

on:
    push:
        branches : ["main"]
jobs:
    build:
        runs-on : ubuntu-latest
        
        steps :
            - name : Chechout
              uses : actions/checkout@v4

            - name : Install Dependencies
              run : npm install

            - name : run
              run : npm run dev

    unit-test :
        runs-on : ubuntu-latest

        steps :

            - name : Checkout
              uses : actions/checkout@v4

            - name : install dependencies
              run : npm install

            - name : dev
              run : npm run dev
